In [2]:
import torch

# Device.
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Cuda

In [3]:
# wait until queued GPU operations are ended.
torch.cuda.synchronize(device)

# Memory measure.
mib = 1024**2
memory_allocated = torch.cuda.memory_allocated(device) / mib, 'MiB'
memory_reserved  = torch.cuda.memory_reserved(device) / mib, 'MiB'

torch.cuda.reset_peak_memory_stats(device)              # reset measuring peak.
peak = torch.cuda.max_memory_allocated(device) / mib    # peak since reset.

# Tensor

In [4]:
size = (3, 3)

# torch.empty() : uninitiallized values.
x = torch.empty(
    size=size,
    dtype=torch.float32,
    device=device,
    requires_grad=False,
    pin_memory=False,       # work only for CPU tensors.
)
print(f"torch.empty()\n{x}\n")

# torch.zeros(): zeros
x = torch.zeros(size)
print(f"torch.zeros()\n{x}\n")

# torch.ones(): ones.
x = torch.ones(size)
print(f"torch.ones()\n{x}\n")

# torch.triu(): left-bottom=0, upper-right=1.
x = torch.triu(
    torch.ones(size),
    diagonal=1,     # 0 = exact diagonal.
)
print(f"torch.triu()\n{x}\n")

# torch.tril(): left-bottom=0, upper-right=1.
x = torch.tril(
    torch.ones(size),
    diagonal=0,
)
print(f"torch.tril()\n{x}\n")


torch.empty()
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')

torch.zeros()
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

torch.ones()
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

torch.triu()
tensor([[0., 1., 1.],
        [0., 0., 1.],
        [0., 0., 0.]])

torch.tril()
tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])



# Random numbers

In [5]:
size = (5, 5)
x = torch.randn(size)
print(f"randn()\n{x}\n")

x = torch.randint(
    low=0,
    high=10,
    size=size,
    dtype=torch.long,
    device=device,
)
print(f"randint()\n{x}\n")

randn()
tensor([[-1.0802, -0.5679, -1.1549,  1.2637,  0.5071],
        [ 2.0515,  0.0215, -1.5268,  1.2464, -0.4341],
        [ 1.2162,  0.5973,  0.7026,  0.8981, -0.4885],
        [ 0.7421,  1.6041, -0.5511, -1.2499, -0.4231],
        [ 0.3404, -1.1025, -0.4634,  0.1137, -0.3060]])

randint()
tensor([[2, 7, 4, 2, 3],
        [6, 0, 8, 3, 3],
        [0, 2, 1, 5, 9],
        [8, 5, 7, 8, 8],
        [7, 7, 8, 2, 4]], device='cuda:0')

